#!/usr/bin/perl
use strict;
use warnings;

my $src = shift @ARGV or die "Usage: $0 user/proj[/branch]";
my ($user, $proj, $branch) = split m{/}, $src;
$branch = 'master' unless defined $branch;

my $url = "http://github.com/$user/$proj/tarball/$branch";

exec 'cpanm', $url;
die "cannot exec: $!";

