#!/usr/bin/env perl
use strict;
use warnings;
use autodie;
use 5.12.0;
use Pod::Usage;

MAIN(@ARGV); exit;

sub MAIN {
    # TODO: search from FrePAN API if network connection is available.
    my ($module) = @_;
    pod2usage() unless $module;

    my $basedir = sub {
        open my $fh, '<', "$ENV{HOME}/.minicpanrc";
        while (<$fh>) {
            chomp;
            if (/^local\s*:\s*(.+?)$/) {
                return $1;
            }
        }
        die "Cannot detect local minicpan direcotry from .minicpanrc";
    }->();
    system "zgrep", $module, "$basedir/modules/02packages.details.txt.gz";
}

__END__

=head1 SYNOPSIS

    % cpan-search Foo

